services:
  app:
    container_name: preliminary_analysis_tool
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
    - ./:/preliminary_analysis_tool/
    ports:
    - '${STREAMLIT_PORT}:${STREAMLIT_PORT}'
    healthcheck:
      test: ["CMD-SHELL", "curl", '--fail', 'http://localhost:${STREAMLIT_PORT}/_stcore/health']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
